[behave]
# 配置behave的输出格式和行为
format = pretty
stdout_capture = false
stderr_capture = false
logging_level = DEBUG
logging_format = %(asctime)s - %(name)s - %(levelname)s - %(message)s
logging_clear_handlers = false
