# Documentation for ACL policy: https://aka.ms/gim/docs/policy/acl

name: Access control list
description: List of teams and their permission levels
resource: repository
where:
configuration:
  manageAccess:
  - member: liujingping
    role: Maintain
  - member: toyu
    role: Maintain
  - member: qunmi
    role: Maintain
  - member: yuexiong
    role: Maintain
  - member: zhengdawang
    role: Maintain
  - member: v-minya
    role: Write
  - member: v-doshen
    role: Write
  - member: v-baji
    role: Write
  - member: v-wangxiaofe
    role: Write
  - member: v-zhulu
    role: Write
  - member: v-xianmyang
    role: Write
  - member: v-chenyshen
    role: Write
